[package]
name = "admit_book"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", default-features = false, features = ["clock"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
